# See default at https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Exclude:
    - 'recipes/*_test.rb'

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 160

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 6

Style/FileName:
  Exclude:
    - 'lib/ilo-sdk.rb'

Style/IndentationWidth:
  Width: 2

Style/VariableName:
  EnforcedStyle: snake_case

Style/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleCamelCase:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/Next:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
